openapi: "3.0.1"
info:
  title: "HelpOnSpot API"
  description: "This is the API documentation for the HelpOnSport backend."
  version: "0.1"
externalDocs:
  description: "Github"
  url: "https://github.com/Helfer-Portal"
servers:
  - url: "https://q7trxhcc49.execute-api.eu-central-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "dev"
tags:
  - name: "User"
  - name: "Organisation"
  - name: "Request"
  - name: "Qualifications"
paths:
  /users:
    get:
      tags:
        - "User"
      summary: "Returns all users"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting users"
          content: {}
        200:
          description: "List of users"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/user"
    post:
      tags:
        - "User"
      summary: "Creates a user"
      description: "Creates a user."
      requestBody:
        description: "Contains the user information"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/profile"
        required: true
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while creating a user"
          content: {}
        201:
          description: "Returns the newly created user"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
  /users/{userId}:
    get:
      tags:
        - "User"
      summary: "Returns a user by id"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the user to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting a user from database"
          content: {}
        200:
          description: "Get successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
    delete:
      tags:
        - "User"
      summary: "Deletes a user by id"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the user to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting a user from database"
          content: {}
        200:
          description: "Deletion successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
  /users/{userId}/profile:
    get:
      tags:
        - "User"
      summary: "Returns a user's profile"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the user's profile to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting a user from database"
          content: {}
        200:
          description: "Get successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
    patch:
      tags:
        - "User"
      summary: "Update a user's profile"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the user's profile to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting a user from database"
          content: {}
        200:
          description: "Get successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profile"
  /users/{userId}/requests:
    get:
      tags:
        - "User"
      summary: "Returns requests, which fit to a user (travelling distance and other filters)"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the user"
          required: true
          schema:
            type: "string"
        - in: query
          name: requestType
          schema:
            type: string
            enum: [accepted, pending, all, declined, matched]
          description: The request type
        - in: query
          name: radius
          schema:
            type: integer
          description: Radius of search
        - in: query
          name: location
          schema:
            $ref: "#/components/schemas/location"
          description: Custom location
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting a user from database"
          content: {}
        200:
          description: "Get successful"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/request"

  /requests:
    post:
      tags:
        - "Request"
      summary: "Create a request"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while creating request"
          content: {}
        200:
          description: "Created request"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/request"
  /requests/{requestId}:
    get:
      tags:
        - "Request"
      summary: "Returns a request by id"
      parameters:
        - name: "requestId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting request"
          content: {}
        200:
          description: "Returned request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/request"
    delete:
      tags:
        - "Request"
      summary: "Deletes a request by id"
      parameters:
        - name: "requestId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while deleting request"
          content: {}
        200:
          description: "Deleted request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/request"
  /requests/{requestId}/volunteers:
    get:
      tags:
        - "Request"
      summary: "Return all matched volunteers for one request"
      parameters:
        - name: "requestId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting request"
          content: {}
        200:
          description: "Returned request"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/responseStatus"
  /requests/{requestId}/volunteers/{userId}:
    put:
      tags:
        - "Request"
      summary: "Add user response to a request"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
        - name: "requestId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
        - name: "response"
          in: "path"
          description: "User response"
          required: true
          schema:
            type: string
            enum: [accept,decline]
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting request"
          content: {}
        200:
          description: "Updated request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/request"
    delete:
      tags:
        - "Request"
      summary: "Remove participant from request"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
        - name: "requestId"
          in: "path"
          description: "ID of the request to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting request"
          content: {}
        200:
          description: "Returned request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/request"
  /requests/{requestId}/invite:
    post:
      tags:
        - "Request"
      summary: "Invite volunteers"
      description: "Invite all matching volunteers to a request"
      parameters:
        - name: "requestId"
          in: "path"
          description: "ID of the request to invite to"
          required: true
          schema:
            type: "string"
      requestBody:
        description: "Array of volunteers, which will be invited"
        content:
          application/json:
            schema:
              type: "array"
              items:
                $ref: "#/components/schemas/user"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while sending invitations"
          content: {}
        200:
          description: "invitation sent"
  /organisations:
    get:
      tags:
        - "Organisation"
      summary: "Returns all organisations"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting organisations"
          content: {}
        200:
          description: "List of organisations"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/organisation"
    post:
      tags:
        - "Organisation"
      summary: "Creates an organization"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting organisations"
          content: {}
        200:
          description: "Created organisations"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/organisation"
  /organisations/{organisationId}:
    get:
      tags:
        - "Organisation"
      summary: "Returns an organisation"
      parameters:
        - name: "organisationId"
          in: "path"
          description: "ID of the organisation to get"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting organisation"
          content: {}
        200:
          description: "Organisation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/organisation"
    delete:
      tags:
        - "Organisation"
      summary: "Deletes an organisation"
      parameters:
        - name: "organisationId"
          in: "path"
          description: "ID of the organisation to delete"
          required: true
          schema:
            type: "string"
      responses:
        400:
          description: "A required parameter is missing or invalid"
          content: {}
        500:
          description: "Error while getting organisation"
          content: {}
        200:
          description: "Organisation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/organisation"
  /organisations/{organisationId}/requests:
    get:
      tags:
        - "Organisation"
      summary: "Returns all request of an organisation"
      parameters:
        - name: "organisationId"
          in: "path"
          description: "ID of the organisation"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Requests"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/request"
  /qualifications:
    get:
      tags:
        - "Qualifications"
      summary: "Returns all qualifications"
      responses:
        200:
          description: "Array of qualifications"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/qualification"
        500:
          description: "Error while getting qualifications"
          content: {}

  /geopoint:
    post:
      requestBody:
        description: "Contains the user information"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/address"
        required: true
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/location"
        500:
          description: 500 response
components:
  schemas:
    request:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "Unique ID"
          format: "int32"
        isActive:
          type: "integer"
          format: "int32"
        start:
          type: "string"
        end:
          type: "string"
        address:
          $ref: "#/components/schemas/address"
    address:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "Unique ID"
          format: "int32"
        street:
          type: "string"
        houseNumber:
          type: "string"
        postalCode:
          type: "string"
        city:
          type: "string"
        country:
          type: "string"
        location:
          $ref: "#/components/schemas/location"
    organisation:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "Unique ID"
          format: "int32"
        name:
          type: "string"
          description: "Organization name"
        logoPath:
          type: "string"
          description: "Path to logo"
        address:
          $ref: "#/components/schemas/address"
        requests:
          type: "array"
          items:
            $ref: "#/components/schemas/request"
    user:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "Unique ID"
          format: "int32"
        lastName:
          type: "string"
          description: "Last name"
        firstName:
          type: "string"
          description: "First name"
        email:
          type: "string"
          description: "Email of user"
    profile:
      type: "object"
      required:
        - email
        - lastName
        - firstName
        - qualities
      properties:
        lastName:
          type: "string"
          description: "Last name"
        firstName:
          type: "string"
          description: "First name"
        email:
          type: "string"
          description: "Email of user"
        isGPSLocationAllowed:
          type: "boolean"
          description: "Boolean for GPS location"
        address:
          $ref: "#/components/schemas/address"
        qualities:
          type: "array"
          description: "Array of user qualities"
          items:
            type: "string"
        avatar:
          type: "string"
          description: "URL to user avatar"
    location:
      type: "object"
      properties:
        latitude:
          type: "string"
          description: "Latitude"
        longitude:
          type: "string"
          description: "Longitude"
    qualification:
      type: "object"
      properties:
        key:
          type: "string"
        name:
          type: "string"
          description: "Translated name"
    responseStatus:
      type: "object"
      properties:
        userId:
          type: "integer"
        reponseStatus:
          type: "string"
          description: "User response to request"
          enum: [accepted, pending, declined]
