AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

# User Pool
  HoSCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: HoSUserPool
        AccountRecoverySetting:
          RecoveryMechanisms: 
              - Name: verified_email
                Priority: 1
        AliasAttributes:
          - email
        # The lambda function to call after user email was confirmed
        #LambdaConfig:
        #  PostConfirmation: arn:aws:lambda:eu-central-1:198891906952:function:HoS_post-user_dev
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: True
            RequireNumbers: True
            RequireSymbols: True
            RequireUppercase: True
        UsernameConfiguration:
          CaseSensitive: True
        Schema:
          - AttributeDataType: String
            Name: 'email'
            Required: True
            Mutable: True
        VerificationMessageTemplate: 
          DefaultEmailOption: CONFIRM_WITH_LINK
          EmailMessageByLink: Welcome to Help On Spot! Please click the link below to verify your email address. {##Verify Email##} 
          EmailSubjectByLink: Your verification link
        AutoVerifiedAttributes:
          - email

  HoSCognitoUserPoolAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties: 
      GroupName: admin
      Description: A group for users with admin privileges
      RoleArn: !GetAtt HoSCognitoAdminRole.Arn
      UserPoolId: !Ref HoSCognitoUserPool          

  HoSCognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: helponspotusers
      UserPoolId: !Ref HoSCognitoUserPool

  GoogleIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref HoSCognitoUserPool
      ProviderName: Google
      ProviderDetails:
        client_id: 712951823298-63bvjn7kmibubnc1pae68egovm3rijo8.apps.googleusercontent.com
        client_secret: _hoFc9vKUSld1S9OnBsQQC5t
        authorize_scopes: profile email openid
      ProviderType: Google
      AttributeMapping:
        email: email

  AmazonIdentityProvider:
    Type: AWS::Cognito::UserPoolIdentityProvider
    Properties:
      UserPoolId: !Ref HoSCognitoUserPool
      ProviderName: LoginWithAmazon
      ProviderDetails:
        client_id: amzn1.application-oa2-client.6ba1a92ede974d9cb370d87475dcc9ba
        client_secret: 18b518226f659d10e3ce62f51ee371fdc8894ade3a817001a05c64d6976ff895
        authorize_scopes: profile
      ProviderType: LoginWithAmazon
      AttributeMapping:
        email: email

  HoSCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DependsOn: 
      - GoogleIdentityProvider
      - AmazonIdentityProvider  
    Properties:
      ClientName: help_on_spot_client
      UserPoolId: !Ref HoSCognitoUserPool
      AllowedOAuthFlowsUserPoolClient: True
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlows:
        - code
        - implicit
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AllowedOAuthScopes:
        - email
        - openid
      CallbackURLs:
        - http://localhost:3000/
        #- other urls e.g. https://helponspot.com/
      LogoutURLs: 
        - http://localhost:3000/
        #- other urls e.g. https://helponspot.com/
      SupportedIdentityProviders:
        - COGNITO
        - Google
        - LoginWithAmazon

# Identity Pool
  HoSCognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      IdentityPoolName: HoSIdentityPool
      CognitoIdentityProviders:
        - ClientId: !Ref HoSCognitoUserPoolClient
          ProviderName: !GetAtt HoSCognitoUserPool.ProviderName

  HoSCognitoIdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref HoSCognitoIdentityPool
      RoleMappings:
        HoSUserPool:
          Type: Token
          AmbiguousRoleResolution: AuthenticatedRole
          IdentityProvider: 
            !Sub 
              - 'cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}:${AppClientId}'
              - CognitoUserPool: !Ref HoSCognitoUserPool
                AppClientId: !Ref HoSCognitoUserPoolClient
      Roles:
        'authenticated': !GetAtt HoSCognitoAuthRole.Arn
        'unauthenticated': !GetAtt HoSCognitoUnauthRole.Arn

  HoSCognitoUnauthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HoSCognitoUnauthRole 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              cognito-identity.amazonaws.com:aud:
              - !Ref HoSCognitoIdentityPool
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr: unauthenticated

  HoSCognitoUnauthPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: HoSCognitoUnauthPolicy
      Roles:
        - !Ref HoSCognitoUnauthRole 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - mobileanalytics:PutEvents
          - cognito-sync:*
          Resource:
          - '*'

  HoSCognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HoSCognitoAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              cognito-identity.amazonaws.com:aud:
              - !Ref HoSCognitoIdentityPool
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr: authenticated

  HoSCognitoAuthPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: HoSCognitoAuthPolicy
      Roles:
        - !Ref HoSCognitoAuthRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'mobileanalytics:PutEvents'
              - 'cognito-sync:*'
              - 'cognito-identity:*'
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - 'execute-api:Invoke'
            Resource:
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/POST/geopoint'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/organisations'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/POST/organisations'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/DELETE/organisations/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/organisations/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/organisations/*/requests'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/POST/organisations/*/requests'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/qualifications'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/DELETE/requests/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/requests/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/POST/requests/*/invite'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/requests/*/volunteers'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/PUT/requests/*/volunteers/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/POST/users'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/DELETE/users/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/users/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/PATCH/users/*'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/users/*/requests'
          - Effect: Deny
            Action:
              - 'execute-api:Invoke'
            Resource:
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/GET/ping'
              - 'arn:aws:execute-api:eu-central-1:198891906952:js7pyl1b87/*/OPTIONS/ping'

  HoSCognitoAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HoSCognitoAdminRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              cognito-identity.amazonaws.com:aud:
              - !Ref HoSCognitoIdentityPool
            ForAnyValue:StringLike:
              cognito-identity.amazonaws.com:amr: authenticated

  HoSCognitoAdminPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: HoSCognitoAdminPolicy
      Roles:
        - !Ref HoSCognitoAdminRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'execute-api:Invoke'
            Resource:
              !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:js7pyl1b87/*'

Outputs:
  HoSCognitoUserPoolId:
      Description: Cognito User Pool Id
      Value: !Ref HoSCognitoUserPool

  HoSCognitoIdentityPoolId:
    Description: Cognito Identity Pool Id
    Value: !Ref HoSCognitoIdentityPool

  HoSCognitoUserPoolClientId:
      Description: Cognito User Pool Client Id
      Value: !Ref HoSCognitoUserPoolClient
